<h1>Python: without numpy or sklearn </h1>

<h3> Q1: Given two matrices please print the product of those two matrices </h3>
<pre>

Ex 1: A   = [[1 3 4]
             [2 5 7]
             [5 9 6]]
      B   = [[1 0 0]
             [0 1 0]
             [0 0 1]]
      A*B = [[1 3 4]
             [2 5 7]
             [5 9 6]]

     
Ex 2: A   = [[1 2]
             [3 4]]
      B   = [[1 2 3 4 5]
             [5 6 7 8 9]]
      A*B = [[11 14 17 20 23]
             [23 30 36 42 51]]
             
Ex 3: A   = [[1 2]
             [3 4]]
      B   = [[1 4]
             [5 6]
             [7 8]
             [9 6]]
      A*B =Not possible
</pre>

In [20]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples


# you can free to change all these codes/structure
# here A and B are list of lists
A   = [[1,3,4],[2,5,7],[5,9,6]]
B   = [[1,0,0],[0,1,0],[0,0,1]]
def matrix_mul(A, B):
    # find no rows and columns of matrix A
    no_row_A=len(A)
    no_col_A=len(A[0])
    
    # find no rows and columns of matrix B
    no_row_B=len(B)
    no_col_B=len(B[0])
    
    if(no_col_A != no_row_B):
        print("Not Possible")
    else:
        product = [[0]*no_row_A for i in range(no_col_B)];
    
    
    for i in range(0, no_row_A):
        for j in range(0, no_col_B):
            for k in range(0, no_row_B):
                product[i][j] = product[i][j] + A[i][k] * B[k][j];   
                  
    print("Product of two matrices: ");  
    for i in range(0, no_row_A):
        for j in range(0, no_col_B):
            print(" ",product[i][j],end=""),  
        print("\n")  
           
matrix_mul(A, B)


Product of two matrices: 
  1  3  4

  2  5  7

  5  9  6



<h3> Q2: Select a number randomly with probability proportional to its magnitude from the given array of n elements</h3>

consider an experiment, selecting an element from the list A randomly with probability proportional to its magnitude.
assume we are doing the same experiment for 100 times with replacement, in each experiment you will print a number that is selected randomly from A.

<pre>
Ex 1: A = [0 5 27 6 13 28 100 45 10 79]
let f(x) denote the number of times x getting selected in 100 experiments.
f(100) > f(79) > f(45) > f(28) > f(27) > f(13) > f(10) > f(6) > f(5) > f(0)
</pre>

In [20]:
from random import uniform
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples


# you can free to change all these codes/structure
def pick_a_number_from_list(A):
    # your code here for picking an element from with the probability propotional to its magnitude
    sum=0
    cumulative_sum=[]
    for i in range(len(A)):
        sum=sum + A[i]
        cumulative_sum.append(sum)
    
    
    U=int(uniform(0,sum))
    print(U)
    number=0
    for i in range(len(cumulative_sum)):
        if(U >= cumulative_sum[i] and U < cumulative_sum[i+1]):
            return number
    

def sampling_based_on_magnitued():
    A = [1, 5, 27, 6, 13, 28, 100, 45, 10, 79]
    a = dict()
    print(A, sum(A))
    for i in range(1,100):
        number = pick_a_number_from_list(A)
        
        if number not in a:
            a[number]=1
        else:
            a[number]+=1
    print(a )

sampling_based_on_magnitued()

[1, 5, 27, 6, 13, 28, 100, 45, 10, 79] 314
78
181
272
156
132
37
58
181
302
248
307
123
234
51
161
172
149
82
256
213
203
202
55
273
161
20
218
47
106
120
235
43
90
69
106
185
268
191
102
53
217
255
136
26
91
159
209
172
237
290
61
166
192
167
200
59
279
253
182
162
185
181
86
0
45
105
106
120
98
196
205
3
249
193
298
89
222
213
155
150
284
260
102
59
59
18
200
215
137
114
26
87
162
109
192
137
299
223
219
{0: 98, None: 1}


<h3> Q3: Replace the digits in the string with #</h3>

consider a string that will have digits in that, we need to remove all the not digits and replace the digits with #
<pre>
Ex 1: A = 234                Output: ###
Ex 2: A = a2b3c4             Output: ###
Ex 3: A = abc                Output:   (empty string)
Ex 5: A = #2a$#b%c%561#      Output: ####
</pre>

In [1]:
import re
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

# you can free to change all these codes/structure
# String: it will be the input to your program
Examples = ['234',
'a2b3c4',
'abc',
'#2a$#b%c%561#']
for Example in Examples:
    new_s = '#' * len(re.sub(r'\D', '', Example))
    print('Input = {} Output = {}'.format(Example, new_s))

Input = 234 Output = ###
Input = a2b3c4 Output = ###
Input = abc Output = 
Input = #2a$#b%c%561# Output = ####


<h3> Q4: Students marks dashboard</h3>

consider the marks list of class students given two lists <br>
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] <br>
Marks = [45, 78, 12, 14, 48, 43, 45, 98, 35, 80] <br>
from the above two lists the Student[0] got Marks[0],  Student[1] got Marks[1] and so on <br><br>
your task is to print the name of students
<strong>a. Who got top 5 ranks, in the descending order of marks</strong> <br>
<strong>b. Who got least 5 ranks, in the increasing order of marks</strong><br>
<strong>d. Who got marks between  &gt;25th percentile &lt;75th percentile, in the increasing order of marks</strong>

<pre>
Ex 1: 
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]
a. 
student8  98
student10 80
student2  78
student5  48
student7  47
b.
student3 12
student4 14
student9 35
student6 43
student1 45
c.
student9 35
student6 43
student1 45
student7 47
student5 48
</pre>

In [2]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

numOfStudents = int(input("Enter the number of students "))
Students = []
Marks = []
print("\nEnter Names")
for i in range(1, numOfStudents+1):
    Students.append(input("Name of student {0} : ".format(i)))
totalMarks = int(input("\nEnter Total Marks : "))
print("\nEnter Obtained Marks")
for i in range(0, numOfStudents): 
    Marks.append(int(input("Mark of student {0} : ".format(Students[i]))))
    
Len = len(Students)
keepTrack = dict()
for i in range(Len): 
    keepTrack[Students[i]] = Marks[i]
    _keepMarks = sorted(keepTrack.values(), reverse = True)
    
def findKey(value):
    for k, v in keepTrack.items():
        if v == value: 
            return k
        
# a. Who got top 5 ranks, in the descending order of marks 
print("\n>Students who got top 5 ranks, in the descending order of marks\n")
for i in range(5):
    value = _keepMarks[i]
    print(findKey(value),"-",value)
    
# b. Who got least 5 ranks, in the increasing order of marks
print("\n>Students who got least 5 ranks, in the increasing order of marks\n")
_keepMarks = sorted(keepTrack.values())
for i in range(5): 
    value = _keepMarks[i] 
    print(findKey(value),"-",value)
    
# d. Who got marks between >25th percentile <75th percentile, in the increasing o
print("\n>Students who got marks between >25th percentile <75th percentile, in th")
for i in range(numOfStudents):
      value = _keepMarks[i]
      if((0.25*totalMarks) < value < (0.75*totalMarks)):
        value = _keepMarks[i] 
        print(findKey(value),"-",value)
    


Enter the number of students 10

Enter Names
Name of student 1 : Student1
Name of student 2 : Student2
Name of student 3 : Student3
Name of student 4 : Student4
Name of student 5 : Student5
Name of student 6 : Student6
Name of student 7 : Student7
Name of student 8 : Student8
Name of student 9 : Student9
Name of student 10 : Student10

Enter Total Marks : 100

Enter Obtained Marks
Mark of student Student1 : 45
Mark of student Student2 : 78
Mark of student Student3 : 12
Mark of student Student4 : 14
Mark of student Student5 : 48
Mark of student Student6 : 43
Mark of student Student7 : 47
Mark of student Student8 : 98
Mark of student Student9 : 35
Mark of student Student10 : 80

>Students who got top 5 ranks, in the descending order of marks

Student8 - 98
Student10 - 80
Student2 - 78
Student5 - 48
Student7 - 47

>Students who got least 5 ranks, in the increasing order of marks

Student3 - 12
Student4 - 14
Student9 - 35
Student6 - 43
Student1 - 45

>Students who got marks between >25th p

<h3> Q5: Find the closest points</h3>

consider you have given n data points in the form of list of tuples like S=[(x1,y1),(x2,y2),(x3,y3),(x4,y4),(x5,y5),..,(xn,yn)] and a point P=(p,q) <br> your task is to find 5 closest points(based on cosine distance) in S from P
<br>cosine distance between two points (x,y) and (p,q) is defind as $cos^{-1}(\frac{(x\cdot p+y\cdot q)}{\sqrt(x^2+y^2)\cdot\sqrt(p^2+q^2)})$
<pre>
Ex:

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1)(6,0),(1,-1)]
P= (3,-4)
<img src='https://i.imgur.com/vIFPOcG.jpg', width=300>
Output:
(6,-7)
(1,-1)
(6,0)
(-5,-8)
(-1,-1)
</pre>

In [6]:
import math


def closest_points_to_p(S, P):
    total_list_of_closest_points_to_p = []
    result_closest_to_p = []

    for point in S:
        denominator = math.sqrt((point[0] ** 2) + (point[1] ** 2)) * math.sqrt((P[0] ** 2) + (P[1] ** 2))
        numerator = point[0] * P[0] + point[1] * P[1]

        if denominator != 0:
            cosine_distance_for_this_point = math.acos(numerator / denominator)
            total_list_of_closest_points_to_p.append((cosine_distance_for_this_point, point))

    

    for item in sorted(total_list_of_closest_points_to_p, key=lambda x: x[0])[:5]:
        
        result_closest_to_p.append(item[1])

    return result_closest_to_p


S = [(1, 2), (3, 4), (-1, 1), (6, -7), (0, 6), (-5, -8), (-1, -1), (6, 0), (1, -1)]
P = (3, -4)

closest_points = closest_points_to_p(S, P)
print("5 Closest point to P based on cosine-distance:", *[point for point in closest_points], sep="\n")

5 Closest point to P based on cosine-distance:
(6, -7)
(1, -1)
(6, 0)
(-5, -8)
(-1, -1)


<h3> Q6: Find Which line separates oranges and apples</h3>
consider you have given two set of data points in the form of list of tuples like 
<pre>
Red =[(R11,R12),(R21,R22),(R31,R32),(R41,R42),(R51,R52),..,(Rn1,Rn2)]
Blue=[(B11,B12),(B21,B22),(B31,B32),(B41,B42),(B51,B52),..,(Bm1,Bm2)]
</pre>
and set of line equations(in the string formate, i.e list of strings)
<pre>
Lines = [a1x+b1y+c1,a2x+b2y+c2,a3x+b3y+c3,a4x+b4y+c4,..,K lines]
Note: you need to string parsing here and get the coefficients of x,y and intercept
</pre>
your task is to for each line that is given print "YES"/"NO", you will print yes, if all the red points are one side of the line and blue points are other side of the line, otherwise no
<pre>
Ex:
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
<img src='https://i.imgur.com/DoQf7mE.jpg' width=400>
Output:
YES
NO
NO
YES
</pre>

In [9]:
import math
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings
    
# you can free to change all these codes/structure
def i_am_the_one(red,blue,line):
    # your code
    sign_of_r_pts_eq = -1

    if eval(line.replace('x', '*%s' % red[0][0]).replace('y', '*%s' % red[0][1])) > 0:
        sign_of_r_pts_eq = 1

    for r_pt in red:
        if sign_of_r_pts_eq == 1 and eval(
                line.replace('x', '*%s' % r_pt[0]).replace('y', '*%s' % r_pt[1])) < 0:
            return 'NO'

        if sign_of_r_pts_eq == -1 and eval(
                line.replace('x', '*%s' % r_pt[0]).replace('y', '*%s' % r_pt[1])) > 0:
            return 'NO'


    sign_of_b_pts_eq = -1 * sign_of_r_pts_eq

    for b_pts in blue:
        if sign_of_b_pts_eq == 1 and eval(
                line.replace('x', '*%s' % b_pts[0]).replace('y', '*%s' % b_pts[1])) < 0:
            return 'NO'

        if sign_of_b_pts_eq == -1 and eval(
                line.replace('x', '*%s' % b_pts[0]).replace('y', '*%s' % b_pts[1])) > 0:
            return 'NO'

    return 'YES'

Red = [(1, 1), (2, 1), (4, 2), (2, 4), (-1, 4)]
Blue = [(-2, -1), (-1, -2), (-3, -2), (-3, -1), (1, -3)]

Lines = ["1x+1y+0", "1x-1y+0", "1x+0y-3", "0x+1y-0.5"]

for i in Lines:
    yes_or_no = i_am_the_one(Red, Blue, i)
    print(yes_or_no)

YES
NO
NO
YES


<h3> Q7: Filling the missing values in the specified formate</h3>
You will be given a string with digits and '\_'(missing value) symbols you have to replace the '\_' symbols as explained 
<pre>
Ex 1: _, _, _, 24 ==> 24/4, 24/4, 24/4, 24/4 i.e we. have distributed the 24 equally to all 4 places <br>
Ex 2: 40, _, _, _, 60 ==> (60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5 ==> 20, 20, 20, 20, 20 i.e. the sum of (60+40) is distributed qually to all 5 places<br>
Ex 3: 80, _, _, _, _  ==> 80/5,80/5,80/5,80/5,80/5 ==> 16, 16, 16, 16, 16 i.e. the 80 is distributed qually to all 5 missing values that are right to it<br>
Ex 4: _, _, 30, _, _, _, 50, _, _  
==> we will fill the missing values from left to right 
    a. first we will distribute the 30 to left two missing values (10, 10, 10, _, _, _, 50, _, _)
    b. now distribute the sum (10+50) missing values in between (10, 10, 12, 12, 12, 12, 12, _, _) 
    c. now we will distribute 12 to right side missing values (10, 10, 12, 12, 12, 12, 4, 4, 4)
</pre>
for a given string with comma seprate values, which will have both missing values numbers like ex: "_, _, x, _, _, _"
you need fill the missing values

Q: your program reads a string like ex: "_, _, x, _, _, _" and returns the filled sequence

Ex: 
<pre>
Input1: "_,_,_,24"
Output1: 6,6,6,6

Input2: "40,_,_,_,60"
Output2: 20,20,20,20,20

Input3: "80,_,_,_,_"
Output3: 16,16,16,16,16

Input4: "_,_,30,_,_,_,50,_,_"
Output4: 10,10,12,12,12,12,4,4,4
</pre>



In [12]:
def curve_smoothing(string):
    list_1=string.split(',')
    for i in range(len(list_1)):
        if list_1[i].isdigit():
            for j in range(i+1):
                list_1[j]=int(list_1[i])//(i+1)
            new_id=i
            new_value=int(list_1[i])
            break
    for i in range(new_id+1,len(list_1)):
        if list_1[i].isdigit():
            temp=(new_value+int(list_1[i]))//(i-new_id+1)
            for j in range(new_id,i+1):
                list_1[j]=temp
            new_id=i
            new_value=int(list_1[i])
    try:
        for i in range(new_id+1,len(list_1)):
            if not(list_1[i].isdigit()):
                count=list_1.count('_')
                break
        temp1=new_value//(count+1)
        for i in range(new_id,len(list_1)):
            list_1[i]=temp1
    except:
        pass
    return list_1


S=  "80,_,_,_,_"
smoothed_values= curve_smoothing(S)
print(smoothed_values)

[16, 16, 16, 16, 16]


<h3> Q8: Filling the missing values in the specified formate</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns
1. the first column F will contain only 5 uniques values (F1, F2, F3, F4, F5)
2. the second column S will contain only 3 uniques values (S1, S2, S3)
<pre>
your task is to find
a. Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3)
b. Probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3)
c. Probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3)
d. Probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3)
e. Probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3)
</pre>
Ex:

<pre>
[[F1,S1],[F2,S2],[F3,S3],[F1,S2],[F2,S3],[F3,S2],[F2,S1],[F4,S1],[F4,S3],[F5,S1]]

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
d. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
e. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3
</pre>




In [14]:
def compute_conditional_probabilites(B,C):
    # your code
    # print the output as per the instructions
    num = 0
    denom = 0
    for i in range(len(A)):
        if(A[i][1] == C):
            denom = denom + 1
            if(A[i][0] == B):
                num = num+ 1
    print('P(B = {} | C == {}) = {}/{}'.format(B, C, str(num), str(denom)))
    # print the output as per the instructions

A = [['F1','S1'],['F2','S2'],['F3','S3'],['F1','S2'],['F2','S3'],['F3','S2'],['F2','S1'],['F4','S1'],['F4','S3'],['F5','S1']]

for i in ['F1', 'F2', 'F3', 'F4', 'F5']:
    for j in ['S1', 'S2', 'S3']:
        compute_conditional_probabilites(i, j)

P(B = F1 | C == S1) = 1/4
P(B = F1 | C == S2) = 1/3
P(B = F1 | C == S3) = 0/3
P(B = F2 | C == S1) = 1/4
P(B = F2 | C == S2) = 1/3
P(B = F2 | C == S3) = 1/3
P(B = F3 | C == S1) = 0/4
P(B = F3 | C == S2) = 1/3
P(B = F3 | C == S3) = 1/3
P(B = F4 | C == S1) = 1/4
P(B = F4 | C == S2) = 0/3
P(B = F4 | C == S3) = 1/3
P(B = F5 | C == S1) = 1/4
P(B = F5 | C == S2) = 0/3
P(B = F5 | C == S3) = 0/3


<h3> Q9: Given two sentances S1, S2</h3>
You will be given two sentances S1, S2 your task is to find 
<pre>
a. Number of common words between S1, S2
b. Words in S1 but not in S2
c. Words in S2 but not in S1
</pre>

Ex: 
<pre>
S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
Output:
a. 7
b. ['first','F','5']
c. ['second','S','3']
</pre>

In [16]:
def string_features(S1, S2):
    # your code
    S1 = S1.split(" ")
    S1 = set(S1)
    S2 = S2.split(" ")
    S2 = set(S2)
    x = len(S1.intersection(S2)) #Number of common words between S1, S2
    y = list(S1 - S2)            #Words in S1 but not in S2
    z = list(S2 - S1)            #Words in S2 but not in S1
    return x,y,z

S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
x,y,z= string_features(S1, S2)
print(x)
print(y)
print(z

7
['F', '5', 'first']
['S', 'second', '3']


<h3> Q10: Given two sentances S1, S2</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns

a. the first column Y will contain interger values <br>
b. the second column $Y_{score}$ will be having float values <br>
Your task is to find the value of $f(Y,Y_{score}) = -1*\frac{1}{n}\Sigma_{for each Y,Y_{score} pair}(Ylog10(Y_{score})+(1-Y)log10(1-Y_{score}))$ here n is the number of rows in the matrix
<pre>
Ex:
[[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
output:
0.4243099
</pre>
$\frac{-1}{8}\cdot((1\cdot log_{10}(0.4)+0\cdot log_{10}(0.6))+(0\cdot log_{10}(0.5)+1\cdot log_{10}(0.5)) + ... + (1\cdot log_{10}(0.8)+0\cdot log_{10}(0.2)) )$

In [18]:
from math import log

# you can free to change all these codes/structure
def compute_log_loss(A):
    # your code
    l = 0
    for row in A:
        l += (row[0] * log(row[1], 10)) + ((1 - row[0]) * log(1 - row[1], 10))
        log_l = -1 * l / len(A)
    return log_l

A = [[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
l = compute_log_loss(A)
print(l)

0.42430993457031635
